## DISABLED WORKFLOW BACKUP
# Archived copy of `vercel-debug.yml`. Moved out of workflows directory to disable execution.

name: ARCHIVED - Vercel Debug (disabled)

on:
  workflow_dispatch:

jobs:
  list-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        run: |
          echo "VERCEL_ORG_ID=${VERCEL_ORG_ID:-<not-set>}"
          echo "VERCEL_PROJECT_ID=${VERCEL_PROJECT_ID:-<not-set>}"

      - name: NOTE
        run: |
          echo "This is an archived debug workflow moved out of the active workflows directory."
